### PR TITLE
feat: added sitemap and updated links

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- This PR adds `sitemap` feature which can help in terms of the SEO
- Updated links to `https://github.com/tigerbeetle/` from the previous one

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@eatonphil Apologies for the ping here, Could you please let me know if there is any update on this PR or if any changes are necessary? 😶

**Comment by jorangreef** [comment]
Thanks @adithyaakrishna! (Phil is no longer at TigerBeetle)

This looks good, regarding fixing the repo names.

However, could you please remove the sitemap (and corresponding NPM module imports) so that there are no lockfile changes? We're happy for search engines to follow links directly.

**Comment by matklad** [comment]
Yup, looks like we indeed don't need a sitemap, as everythig is comprehensively linked already, as per:

https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview

I've pulled the tigerbeetledb changes into https://github.com/tigerbeetle/tigerbeetle/commit/fddc78c51a0dd1cb42c86ec1533db9e032ac5ff9 while moving the code from here over to the main repo.

Thanks for noticing this, @adithyaakrishna!

**Comment by adithyaakrishna** [comment]
I don't know how I missed these notifications, apologies for the same and thanks @matklad for pulling those changes. Though it was a minor contribution from my end, I'm happy about it :)

**Pull request closed without merging**
